services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password!"
      ACCEPT_EULA: "Y"